# Generated by Django 4.2.23 on 2025-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10),
        ),
    ]
